<a href="https://colab.research.google.com/github/necmigunduz/ml-professional/blob/main/ML_10_29_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Variables

In [ ]:
x = 3

In [ ]:
c = 2 + 4j

In [ ]:
d = "Necmi"

In [ ]:
e = 4.5

In [ ]:
names = ["Ahmet", "Ayşe", "Hamdi", "Haydar", "Hayri", "İlke", "Cumhur", "Huriye", "Necmi", "Tina", "Niyazi", "Ömer"]

In [ ]:
for name in names:
    name = name.upper()
    if name.startswith("A" or "E" or "I" or "İ" or "O" or "U" or "Ü" or "Ö"):
        print(name)

AHMET
AYŞE


In [1]:
%whos


Interactive namespace is empty.


In [ ]:
print(type(x))

<class 'int'>


In [ ]:
def average(nums):
  # nums should be an array
  sum = 0
  for num in nums:
    sum += num
  return sum / len(nums)


In [ ]:
average([9,1,2,4,1])

3.4

In [ ]:
import numpy as np
import sys


In [ ]:
array = np.array([1,2,3,4])
for num in array:
  print(num)

1
2
3
4


In [ ]:
b = np.array([[1,2,3],[2,3,4]], dtype='int32')
for arr in b:
  for num in arr:
    if num%2==0:
      print(num)

2
2
4


In [ ]:
print(f'Dimension: {b.ndim}, Shape: {b.shape}, Size: {b.size}, Type: {b.dtype}, Itemsize: {b.itemsize}, Number of bytes: {b.nbytes}')

Dimension: 2, Shape: (2, 3), Size: 6, Type: int32, Itemsize: 4, Number of bytes: 24


In [ ]:
c = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
c[0:1]

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
c[0, :]

array([1, 2, 3, 4, 5, 6])

In [ ]:
c[:,2]

array([3, 9])

In [ ]:
c[1, 2:7:1]

array([ 9, 10, 11, 12])

In [ ]:
c[1,3] = 19
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 19, 11, 12]])

In [ ]:
c[:,3] = 32, 23
c

array([[ 1,  2,  3, 32,  5,  6],
       [ 7,  8,  9, 23, 11, 12]])

In [ ]:
d = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])

In [ ]:
d[0:2]

array([[1, 2],
       [3, 4]])

In [ ]:
e = d = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
e[:,1,0]

array([ 3,  7, 11])

In [39]:
import seaborn as sns
import pandas

In [40]:
titanic_data = sns.load_dataset("titanic")
print(titanic_data.head())
print(titanic_data.info)

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
<bound method DataFrame.info of      survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female

In [41]:
print(titanic_data.describe())

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200


In [42]:
missing_values = titanic_data.isnull().sum()
print(f'Missing Values in the Titanic Data:\n{missing_values}')

Missing Values in the Titanic Data:
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64


In [43]:
titanic_data["age"].fillna(titanic_data["age"].median(), inplace=True)
titanic_data.isnull().sum()

/tmp/ipython-input-1784930849.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic_data["age"].fillna(titanic_data["age"].median(), inplace=True)


survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [44]:
new_titanic_data = titanic_data.drop(columns="embark_town")
new_titanic_data.notnull().sum()

survived      891
pclass        891
sex           891
age           891
sibsp         891
parch         891
fare          891
embarked      889
class         891
who           891
adult_male    891
deck          203
alive         891
alone         891
dtype: int64