<a href="https://colab.research.google.com/github/necmigunduz/ml-professional/blob/main/ML_10_29_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Variables

In [2]:
x = 3

In [3]:
c = 2 + 4j

In [4]:
d = "Necmi"

In [5]:
e = 4.5

In [6]:
names = ["Ahmet", "Ayşe", "Hamdi", "Haydar", "Hayri", "İlke", "Cumhur", "Huriye", "Necmi", "Tina", "Niyazi", "Ömer"]

In [7]:
for name in names:
    name = name.upper()
    if name.startswith("A" or "E" or "I" or "İ" or "O" or "U" or "Ü" or "Ö"):
        print(name)

AHMET
AYŞE


In [8]:
%whos


Variable   Type       Data/Info
-------------------------------
c          complex    (2+4j)
d          str        Necmi
e          float      4.5
name       str        ÖMER
names      list       n=12
x          int        3


In [9]:
print(type(x))

<class 'int'>


In [10]:
def average(nums):
  # nums should be an array
  sum = 0
  for num in nums:
    sum += num
  return sum / len(nums)


In [11]:
average([9,1,2,4,1])

3.4

In [12]:
import numpy as np
import sys


In [13]:
array = np.array([1,2,3,4])
for num in array:
  print(num)

1
2
3
4


In [14]:
b = np.array([[1,2,3],[2,3,4]], dtype='int32')
for arr in b:
  for num in arr:
    if num%2==0:
      print(num)

2
2
4


In [15]:
print(f'Dimension: {b.ndim}, Shape: {b.shape}, Size: {b.size}, Type: {b.dtype}, Itemsize: {b.itemsize}, Number of bytes: {b.nbytes}')

Dimension: 2, Shape: (2, 3), Size: 6, Type: int32, Itemsize: 4, Number of bytes: 24


In [32]:
c = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
c[0:1]

array([[1, 2, 3, 4, 5, 6]])

In [34]:
c[0, :]

array([1, 2, 3, 4, 5, 6])

In [38]:
c[:,2]

array([3, 9])

In [43]:
c[1, 2:7:1]

array([ 9, 10, 11, 12])

In [52]:
c[1,3] = 19
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 19, 11, 12]])

In [61]:
c[:,3] = 32, 23
c

array([[ 1,  2,  3, 32,  5,  6],
       [ 7,  8,  9, 23, 11, 12]])

In [63]:
d = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])

In [73]:
d[0:2]

array([[1, 2],
       [3, 4]])

In [90]:
e = d = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
e[:,1,0]

array([ 3,  7, 11])